name: coding-club
channels:
  - conda-forge
dependencies:
  - python=3.10.9
  - pip=23.0
  - setuptools=67.1.0
  - matplotlib=3.6.3
  - click=8.1.3
  - ipython=7.33.0
  - pandoc=2.17.1.1
  - livereload=2.6.3
  - libsass=0.21.0
